export const EVENT_CATEGORIES = {
    WORKSHOP: "WORKSHOP",
    HACKATHON: "HACKATHON",
    MEETUP: "MEETUP",
    GRANT_SPRINT: "GRANT_SPRINT",
};

export const EVENT_STATUS = {
    DRAFT: "DRAFT",
    PUBLISHED: "PUBLISHED",
    CANCELLED: "CANCELLED",
    COMPLETED: "COMPLETED",
};
